apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
spec:
  valuesContent: |-
    nodeSelector:
      hoganlab/location: cloud
    ports:
      web:
        exposedPort: 80
      websecure:
        exposedPort: 443
      matrixfed:
        port: 8448
        exposedPort: 8448
        expose:
          default: true
        protocol: TCP
        tls:
          enabled: true
    service:
      spec:
        externalTrafficPolicy: Local
      
    volumes:
      - name: configmap-routes
        mountPath: /config/dynamic
        type: configMap
    additionalArguments:
      - --providers.file.directory=/config/dynamic
      - --providers.file.watch=true
      - --entryPoints.web.http.redirections.entryPoint.to=:443
      - --entryPoints.web.http.redirections.entryPoint.scheme=https
      - --entryPoints.web.http.redirections.entryPoint.permanent=true
