apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
spec:
  valuesContent: |-
    ports:
      web:
        exposedPort:4480
        forwardedHeaders:
          insecure: true
      websecure:
        exposedPort: 4443
    volumes:
      - name: configmap-routes
        mountPath: /config/dynamic
        type: configMap
    additionalArguements:
      - --providers.file.directory=/config/dynamic
      - --providers.file.watch=true
