apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmchartconfig.yaml
  - configmap-routes.yaml
  - certificate-wildcard-hogans-at.yaml
  - certificate-wildcard-eaglecomputerrepairsc-com.yaml
  - tlsstore-default.yaml
