apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: freshrss
labels:
  - pairs:
      app.kubernetes.io/name: freshrss
      app.kubernetes.io/part-of: hoganlab
    includeSelectors: false
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - networkPolicy-traefik-in.yaml
  - networkPolicy-https-out.yaml
components:
  - ../../components/netpol-baseline

