---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hetzner-token-hogans-at
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAk5/5IhhYEWCndQH6+8sngYLxCDSASiAO2CivW+2eFp4vEdXcytDk2m5WsiGXQGPoDdfmwBZEuSfGHgrdvGyGEy6/OQ7x7QlHnQMPnyCPdwjZN6VqTkhfbRT6+KcL6IE+siatc3DgERK48ufaolSrYht/l2qtZ35Ou1aFaQzafBgvXqIsnYxBHscmFEd9Rio+5p13DvS9BSisM/nZVT8gxpxhYgodmRhekCVKg3IWHeKTakkNTlxvcCp5y6KSdXQq8ezRryBeh/xQoDAWD3yS7/xg2uF8MCZelgxXD8Uh6ZJ1tEFt6+F7hO2jKRsdlRDhmmQb1VEa2sPB1m/wA4pgG0tjwC3UofSIifm+eFX0APqJMUWRK5eBEc6R3uVnbE9cCxWkHeUKVzXydToQNZwtjm4PBnTlmB7tOWhWhxb7/4bNwn+0FEkme100H4swpR/bk+ig9Ur9tOAO7Of92xyEOB+gLB3+HkU1F6M4pwdiNxYmmrLuCGZjCaVUwqrhwDKWdTGVIcLgkWc+00wE2ZDa3rYX1CAw5I1X1iXlToYFa3wF6sP9g7GN2Oi4yJ9XEk0tpkI4ZpWJxT1eJYTI2b+IWFwIomWGhnTg1gX7/KFREjFWwSjgLuEOm9vAbmNYDcep2LMkkkvTQzlW8XzFZVnu0L9OK7MufcFH9nrvH6pJRuusyXlt5CmnUC83NwxF11tU=
  template:
    metadata:
      name: hetzner-token-hogans-at
      namespace: cert-manager
