---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hetzner-token-eaglecomputerrepairsc-com
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCNtkZtQhPdmgw7c4XsqxxrmvxmxR4Jo/5gLSshdXliAZtICHBNHQWLUqdv/MfEe8fdpa/+13KkPnQAvVxLDLZ7UeVqn3MAhd2Z9nAAPP6KXcb6YFtZDBn5xwDEo+RKoveWfk7TclgVAyZG6kwdi93QYSX3iITIw7vApj8ABkeujQwqkdUynievbP8OshHlL39UBHhtQfsOTqMKPPj0a/OC+Q3CNoW2A/qpQTdajIqUv7aBu/pG5m7YHKz1r37qFZz+jss0fM0u1s/XEtpJ5IzfsAEqkn92gsLmS2GsdVKK/voQmrhtxbg08XxOH9qSQWXG6lRAip9FBegKPpkiHEzGG9cLkG2vJag+aM+1l1rF6XQFIIUNxWC0WRYluScPlHXxh0BqQgFepnSP9vwhmxFg+41dHO0D8HaDPtOQo+YZxWwDXUPuLg4m6A1WrlDve56MCdFSwF42pLXKB6n83IAC9eDmfPCebM/suK/6anldYRbPFM8DznWoZ7NkYa020i0YSIBUogrhKVycGD0ZIo2U+uH4iA+7ELA1wKTU6XZzX5xxZyC23PGkjS5e+CeZ26DqUtDVWxJtBnqBvMW6sZ7HRyURm3sMsAndjz76lxlzM7FVFm+RBju70iU17iBk5aMI2nRSTjIDIZjgAybZc8sdh9dX1ZAVx+Delnt0YaicU0MogLCks1LrvmsCr8zXvenj1GC0TtNvkr1lgNMLcXEG++7OpzK39XbNN+Rm4FEv1j7bp78kSRWgGA6yKoOWQLt/mUN/qN4BT8RzMawmfDjh
  template:
    metadata:
      name: hetzner-token-eaglecomputerrepairsc-com
      namespace: cert-manager
