---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hetzner-token-eaglecomputerrepairsc-com
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAx0hPz4T2Cz00iP2wxOqg19GYELqggp5wL1shu2OLMVmlREPDKZHqnJPryYmiWF/akHIn0oyR3HZOR382jK72OfcMTfAKKRoGwX5E4ZVXgxZSdfszWe/IC4jWvZd9m7ke7UHSYE2843A4bQ2t319KVg0J7qNzNvWjzPUpXuM73oQTyvm2gQwLv0wcyHYT21qGtujsnWPxF8lEhY6nQJa+J06CFp4sj/Ksh4tAHws9RSBFG/vuFJAXTBGiTYfTgJk9LIksPgSjWqcKtNJWWjLijks9PEtiOq4aW4Q1XVNYjpRj6oBuwrLoNjbAQ971Nz4GfSAyL5KFUa//Ijfd392eJclDStyXyxgIUZZjGnwg1Vs3ycjrkG6mqkrlU8AIaqcqrHBo2MpZCdmzb/ynHLslAcIGhuLYBaF1kXSUU9wcEGbppm3Q5DLIB/q6PlQ31yr7Oh6RZsqOaWXVrPA5c4UERO1rhoZWXPQSa4xsJlV0bEPvkpTkxnwpdZ9PhTfbSZ/zqtiEQD+TKOdDocihNMfKU+SBKJItm2J3tHy1NLUtQH742f6uFBm2IvPHukVbj1QWZ+j7kv9uYQVQU0B4gKqBcDD2QfqKPm1wQAksP+vCTQZh18AR5xpDyEdETUNbGN0Du+eiBnr6BhoBM0YklhvCNKXqN3q5u/klDSvYnC7Fg1aCUsfqIMZe3CRjA/tnua12+3bVZgIiItAB6XZqh3ixCaCBVbqCxL4+m/uQ9AolqdL7KUYFP+bvWYRxjyDc+FCn5YEqnlC7Y/oc9q+KhpPXJ
  template:
    metadata:
      name: hetzner-token-eaglecomputerrepairsc-com
      namespace: cert-manager
