---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hetzner-token-hogans-at
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBstsiC6OukgchAAPgSzQsCliTsrgVoERZ3kdeHBTFPGE79/sqBcVnH+j2CXSe9Vax/lL6+5O8jD1rU1N+/pwF/o82Qs0UfSTaVRounRITJJjOhuhJY+uuJpSvzsY/wlvmYy2baDIK+9/ICpYF99BuDMNsdeSaa8d/NS9sfTeJo8V6Clww9VqCpsmaDn/8NKbFF+A7QPnRCvfsSJ+rVoR5n+JPkoeiJEGyzRjZ4+g7LibJ52pFGGgvxFzsrNE7F0AhDtin+TZdwNI0Kxut6gmxtNlwq1kTeI0E1WR57ByC8Ex4lijWALJdkLuDJ2gVKl5N8oV6MLYXoPOsmgUGX/143GkYtXZBNb6L0AeVnwi7tDlsCFkElchOF2ZslE+cbZnAIb96UB+pPbtrYAs8V6NWm1uCaJkamjVHavtyu+ukdUmG20Z+Bozu9Tf9bj0GcOLt3OMLTB8n9KrrxmIuIS+oME2EoI7VHhmnK0MwObO1SzLHIc2bJLqFBmufExUz0ax9YSYKB8paK2oUBiWepfG2Oohe+k1lMnzdqDq85ITZ0l0024Nezepu4AotJUeHM9dDsSAfaQh6cnO/bChllnjB6Val4zospYPCXH++gUgDSImD9ociMVQGehm6K+MifbLNt/q2Snhx57DvpI9ONCC7DgTipUTx7Dw6msF2w+M5Fk7vLPw8dTpBcdHtm9jFjC0YkW7JZ6+s1fjGMi785xwyVpkHc0LzVZ63AKcyVIWTcPLp4oXBFq1Ectn2oLXAUG5pEii/nDrhB6ablU/ukn9GZ
  template:
    metadata:
      name: hetzner-token-hogans-at
      namespace: cert-manager
