---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hetzner-token-hogans-at
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgATHdS3RTOed+bC/oT7tQdrR5STf+nmgypJocCnSvTomK3ibTOkhO6h8TgErmvt/2oOtfl7/abIVo86kL6/KFBASccX/nGmiB9hlcQV/e4SonEMaKMNtHdhrF+HMA71eKXSKopxxd1K5G0XaJLVN2WHIOdGHBX+xItFEDaHu3pBqqlr5bfGJwSXdV2MNPVxk9PxeJ1ICAstvHhxbeSdAoPcLHCFVe7e94pzFSxgCQcqyVB3wPj7xq+IdC5P7Y4KJ2TtcdYgP+D2DEjYPwg/hUkrV4JJYpRtX4C//AztMWvNfZaLIoUI5OUTVF2YS3moO61DPHjOhCFe61N2oIO25gquGez9DxH+d/yP0iYt4rRxF4JxsSszlXkImPu71Rcgsk7GPd1L0hWE8rEEYHa94EXao0pVlwjEeIJnLNw8hYBQk92XVKOI/sS34IC1+sgAzQGnCE540JHVXUpoMuyKc+MGLamMhIOuppi9hZgxBgK4xcT2cqfrjmcXZ72ZQWqDCn9vVIfKnhxACC3P0L3xQAHJMRVR3r9ZMj5g0H9noreOOGtqfez88RzzDVY+9eaqvUHaZGRGH90fsVY6rCEorlGtZKZpLDLuEFr0jYTgoyRLzAyZshKAOhz66dXQ22Uz+vT1fiVazZyK+CLnA7OLNzTtA1EuYKSKLZ5+FuhTRBl0KLTUrq41P4vNxPLUEMgndwqaXLCHDPL5DEoSgYtunx+iY+R0GtESkoTfziCkxDyByNn8eEwq3jpVR1krcUc38TWHFC+Ftufk2eV8Gxo/WJOG
  template:
    metadata:
      name: hetzner-token-hogans-at
      namespace: cert-manager
