---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hetzner-token-eaglecomputerrepairsc-com
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBlz8og/fz60oTSFQPBnfzjG0flzRNIlYJZfLyOE69hfXNzXT77MAUtYGgurmfbvmXWeLu+emKezNnoYbwoHJ69O1PQHOM/7729COky6umsRu37KphCjQrp/CJyVlCPaRjZAMNR34rjMm6T5ouO8+lyfOdbNhkI4UX830DECF8AlDsbLjhCpD5LvlPiCbLRJR5laki/KAg85gZzzEQbM1i5gbC5R4p5Vo4+EIaZUA0so4fwbPT1xWwQUSSuprNbDhBTKbfLdMXSJIUgMGbEebpr8EI0YTTz3VTbTcorKX5cYqWx0HdcKde8HRjdooWaV+PcfipukWDcThvo6beGo82X/BL7JM+yBKg3mGnuwqK3oH5g5f2+il7kR+i96dROGTip+8RgfEkiWHrRcuIsKThXn//+7YN7+1gUGKsyqhWHQfvDIaV9Id6nHRUGtx0h2fMhrZgWmBqHAfvfr3lfqx15BXTJ99iH2edtwLbj3/CyDxf6eEj/UL4Mis30XzyJKkJmij4t5Oq4Jp8UxjzVDPbyL3+23myAuc7xmk7tJr9lEoJNfrbhahzYs85WlzNzGVdvihyjXwbob+ULHoO/Q/1dZm8wgK0hCaPkNXGkHNVeKPfTOU6Tn/bC/WGUOTzB/+MRrBlTw/oe1CkDQo0G3JvDhM5288Iv0hOwMJws6UlmLpXmUF/lpkXTZzCccLOmGsnyFY29DGf1IAA1eDCE0gaWGM4pzBqCTyqfp0C025DGtM+3xphDsxb3zRDcQTXIjnPyzwDrnOfN2gVRAl9zbkH/
  template:
    metadata:
      name: hetzner-token-eaglecomputerrepairsc-com
      namespace: cert-manager
